### ISSUE TITLE
Not able to access repo changes via the UI

### ISSUE THREAD

**Issue by karent** [MakerPress/atlas-public-feedback#417]
When I try to view recent changes by clicking on the Changes button in the UI, I get a 500 error. 

Specifically, I was looking at http://atlas.labs.oreilly.com/books/1234000000598, and I get to http://atlas.labs.oreilly.com/books/1234000000598/versions/master/changes and see "We're sorry, but something went wrong. If you think this is a bug, please report it."

I had this happen with a couple of other v1 books yesterday (sorry I don't recall titles).

**Comment by oskay** [comment]
I see that this issue is closed. Is there a way to avoid the 500 error?

**Comment by sandersk** [comment]
@oskay: any 500 errors are typically due to character encoding issues. If you can point us to the project URL, we can take a look.

**Comment by oskay** [comment]
Interesting. There were encoding errors in prior versions that prevented HTML versions from compiling. Those are corrected now, and PDF and HTML versions compile, but there is still a 500 error when trying to look at changes.

http://ano-atlas2.herokuapp.com/books/1234000002167/versions/master/changes

**Comment by sandersk** [comment]
Ah, I suspect that you're still encountering issues because we've got those character encoding changes preserved in the version history. I don't believe there's a way we can easily rectify here, unfortunately. Sorry for the inconvenience.

Are you comfortable working with git? If so, I would suggest that if you need to review changes, you can clone down a local copy of the repo, and then use "git diff" (http://git-scm.com/docs/git-diff) as needed to see changes.

Hope this helps,
Sanders

**Comment by oskay** [comment]
Yes, I used git. But, that's a workaround.

It would be good if the documentation had something about how to set up files correctly, so that this doesn't happen to other people.

**Comment by sandersk** [comment]
Great, glad you have a workaround. 

We're actually in the process of rolling out to authors a brand-new release of Atlas that will have enhanced collaboration and change-tracking features, as well as better encoding support to avoid issues like those you've experienced. If you're interested in moving to the new system, please let your editor know, and then we can assist with the migration.
