### ISSUE TITLE
PDF export doesn't include page for sidebars

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#70]
In the latest PDF export of http://ano-atlas2.herokuapp.com/books/1230000000581/builds, references to the sidebar named "Assuming a User's Profile" say (page ) without the number included. It's probably because it's a sidebar, but I use sidebars a few times in the document and make cross-references to them, so it might be something to fix.

**Comment by sandersk** [comment]
Hi Stafford,

Thanks very much for bring this issue to our attention. The missing page numbers was actually a bug we inadvertently introduced when attempting to improve sidebar rendering. We've fixed the problem now.

I've gone ahead and done a fresh build of the PDF for your book, and the page numbers are showing up properly now. Please let us know if you spot any more problems, though. We really appreciate the feedback.

Thanks,
Sanders

**Comment by jhodgdon-drp** [comment]
I am still seeing this issue and I think it should be reopened -- there are no page numbers on references to sidebars in a PDF that I just created today.

**Comment by jhodgdon-drp** [comment]
Just to clarify, the reference to the sidebar just says "See [sidebar name]" and does not include a page number at all.
http://ano-atlas2.herokuapp.com/books/1230000000517/builds

**Comment by sandersk** [comment]
Hi Jennifer,

I took a look, and I don't see any sidebars in this book. Sidebars are marked up using asterisks, e.g.:

```
[[sidebar_id]]
.Sidebar Title
****
This is the sidebar content
****
```

Could you point me to a specific example of a cross reference that you wanted to render with a page number, but is not getting a page number? All cross-references to section headings and sidebars should indeed render with page numbers.

Thanks,
Sanders

**Comment by jhodgdon-drp** [comment]
Oh sorry. Maybe it's a separate issue -- it's a [Note] section. In the file preface.asciidoc, there is a section:
'''
[[api_site]]
.Using api.drupal.org
[NOTE]
'''

And when this is referenced (also in the preface), no page numbers are being printed with the reference. Should I open a separate issue since this is not a "sidebar" per se?

**Comment by sandersk** [comment]
Hi Jennifer,

Gotcha. I took a look, I think the note you've got on page ix of the Preface would actually be better formatted as a sidebar. 

It's generally O'Reilly style to reserve notes and warnings for short, one- or two-paragraph admonitions directly related to the body text that precede them. In contrast, we use sidebars for longer, more tangential asides to the main discussion. Authors don't typically do cross-references to Notes, which is why we don't have special handling at this time to generate page numbers for them.

Would it meet the needs of your book to reformat long, cross-referenced Notes like the one on page ix to be sidebars? If not, we can look into some stylesheet tweaks for you to get the desired cross-ref rendering.

Thanks,
Sanders

**Comment by jhodgdon-drp** [comment]
Sure, that sounds like a good idea. I'll take care of it. You might add a note about that to some of your documentation. :)
